- name: Create ~/.local/bin/ directory
  ansible.builtin.file:
    path: "{{ box_homedir }}/.local/bin/"
    state: directory

- name: Create ~/.local/share/fonts/ directory
  ansible.builtin.file:
    path: "{{ box_homedir }}/.local/share/fonts/"
    state: directory
